[package]
name = "tutor-nodb"
version = "0.1.0"
authors = ["ahyz0569"]
edition = "2021"
default-run="tutor-service"

[[bin]]
name = "basic-server"

[[bin]]
name = "tutor-service"

[dependencies]
# Actix web framework & run-time
actix-web = "4.2.1"
actix-rt = "2.7.0"